name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: |
          if [ "$VERCEL_ENV" == "production" ]; then
            echo "Running in Vercel production environment"
            # Add steps specific to Vercel production environment here
          else
            echo "Running in GitHub Actions or Vercel preview environment"
            # Add steps specific to GitHub Actions or Vercel preview environment here
          fi
